language: python

cache:
  directories:
    - $HOME/.cache/pip

python:
  - "3.6"

services:
  - postgresql

# install requirements
install:
  - pip install -r requirements.txt

script:
  - coverage run --source='.' ./manage.py test
  - coverage report

after_script:
  - coveralls
